name: Deploy Angular to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t angular-app-container .

    - name: Push Docker image to DockerHub
      run: |
        docker tag angular-app-container ${{ secrets.DOCKER_USERNAME }}/angular-app-container:latest
        dcker push ${{ secrets.DOCKER_USERNAME }}//angular-app-container:latest


    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/angular-app-container:latest
          docker stop angular-app-container || true
          docker rm angular-app-container || true
          docker run -d --name angular-app-container -p 80:80 ${{ secrets.DOCKER_USERNAME }}/angular-app-container:latest

